name = "nexus-re-api"
main = "src/index.ts"
compatibility_date = "2026-05-27"
workers_dev = true

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "nexus-re-d1"
database_id = "1161e5c3-a173-4aee-93a8-4e93063a04b9"
